### PR TITLE
Fix redirects after logging in

### PR DESCRIPTION
**Pull request by mczuchnowski**
I believe it now works the way you intended.

### CODE REVIEW

**Comment by Yorkshireman** [comment]
In the application controller you wrote a 'not_authenticated' method, but it doesn't seem to get called anywhere??

The remaining method in the application controller is called "require_login_for_new_testimonial", but this is a typo (MY typo :-) ) - it should be called "require_login" - that is the method that is used in the before filter in the testimonials controller.

Now then, so why did it seem to work for you? Well, you fixed the typo "redirect_back_to" to "redirect_back_or_to" in the User Sessions controller's 'create' method. Now... this SHOULD be the solution, I think, but what seems to happen is that, after I make this fix, the FIRST time I check the result, it WORKS i.e. you click on 'Deja tu opinion' when you're not logged in, it takes you to the login page, you login and VOILA - you are directed to the Nuevo Testimonial page.

BUT! When you go back to the home page, logout, refresh, and try all of that again, it doesn't work!!  You get directed back to the home page instead. Very strange!!

By the way, I DID try including your not_authenticated method, too, but it didn't make any difference. And I don't understand why it would, because it doesn't seem to get called anywhere? And why is it in its own private section?

**Comment by mczuchnowski** [comment]
The not_authenticated method is there to override Sorcery's default behavior. It is called by the gem internally, not by you. I got all the info here: http://railscasts.com/episodes/283-authentication-with-sorcery?view=asciicast

**Comment by Yorkshireman** [comment]
DONE IT! :-D

I had written my own method called 'require_login' in the application controller. This shares the same name as Sorcery's own 'require_login' method. That was messing things up.

I can't remember why I wrote that method, but I think I wasn't aware of the fact that Sorcery already had a method with the same name! A co-incidence.

You were right about the not_authenticated method (great link!!) - it looks like its default behaviour is to take you to your root_url. I've written a suitable response for it in the application controller.

Thanks a lot man!!

I've pushed the commit, so you can take a look if you're curious.

Thanks again!

**Comment by mczuchnowski** [comment]
Always happy to help :). I'll fetch the upstream and see how it works. Knowing another authentication gem is always a perk.

**Pull request closed without merging**
